
data:
	curl -Lo data.csv "https://mesonet.agron.iastate.edu/cgi-bin/request/asos.py?station=PWM&data=all&year1=2020&month1=1&day1=1&year2=2021&month2=8&day2=28&tz=Etc%2FUTC&format=onlycomma&latlon=yes&elev=no&missing=M&trace=T&direct=no&report_type=1&report_type=2"
